#!/bin/bash

# Name: setCPUProfile
# Description: Sets the scaling_governor value depending on current state and if there is a VM running.
#              This works with AMD RYZEN CPUs, Intel has different states the script could be modified
#              to use their states very easily.
#              https://wiki.archlinux.org/title/CPU_frequency_scaling#Scaling_governors
# Update: Polling specific VM name "Windows 11 RTX" only for cpu scaling and update to use powersave
#         cpu governor when VM is off and support CPUs upto 16 threads
# Date: Nov 18, 2024
# Author: Jason McLeod, Hilman Chung
# Version: 1.1

isRunning=$(ps axu | grep qemu | grep -c "Windows 11 RTX")
curState=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)

if [ $isRunning -gt 0 ]; then
  echo "VMs are running"
  if ! [ "$curState" == "performance" ]; then
    echo "Enabling performance mode"
    for cpu in /sys/devices/system/cpu/cpu[0-15]*/cpufreq/scaling_governor; do echo "performance" > $cpu; done
  fi
else
  echo "VMs are stopped"
  if ! [ "$curState" == "powersave" ]; then
    echo "Enabling conservative mode"
    for cpu in /sys/devices/system/cpu/cpu[0-15]*/cpufreq/scaling_governor; do echo "powersave" > $cpu; done
  fi
fi
